/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package halaman;

import static halaman.Config.writeLog;
import java.awt.Color;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.SQLException;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kelompok 2
 */

public class FKaryawan extends javax.swing.JFrame {

    private boolean isEditing = false;

    /**
     * Creates new form FKaryawan
     */
    public FKaryawan() {
        initComponents();
        setLocationRelativeTo(null);
        load_table();

    }

    private void load_table() {
        // Membuat tampilan model tabel
        // Membuat tampilan model tabel
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                // Semua sel tidak bisa diedit langsung
                return false;
            }
        };

        // Menambahkan kolom ke tabel
        model.addColumn("No");
        model.addColumn("ID Karyawan");
        model.addColumn("Nama");
        model.addColumn("No. Telepon");
        model.addColumn("Alamat");

        // Hapus data lama dari tabel
        jKaryawan.setModel(model);

        // Menampilkan data dari database ke dalam tabel
        try (java.sql.Connection conn = Config.configDB(); java.sql.Statement stm = conn.createStatement(); java.sql.ResultSet res = stm.executeQuery("SELECT id_karyawan, nama, no_telp, alamat FROM t_karyawan")) {

            int no = 1; // Nomor urut
            while (res.next()) {
                model.addRow(new Object[]{
                    no++, // No urut
                    res.getString("id_karyawan"), // ID Karyawan
                    res.getString("nama"), // Nama
                    res.getString("no_telp"), // No Telepon
                    res.getString("alamat") // Alamat
                });
            }

            // Jika data kosong, beri informasi ke pengguna
            if (model.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Data karyawan tidak tersedia.", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Data tidak dapat ditampilkan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtKaryawan = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtNoTelp = new javax.swing.JTextField();
        jScrollPanel1 = new javax.swing.JScrollPane();
        jAlamat = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jKaryawan = new javax.swing.JTable();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        jUtama = new javax.swing.JLabel();
        jPelanggan = new javax.swing.JLabel();
        jTransaksi = new javax.swing.JLabel();
        jLayanan = new javax.swing.JLabel();
        jKaryawan1 = new javax.swing.JLabel();
        jTentang = new javax.swing.JLabel();
        jKeluar = new javax.swing.JLabel();
        jDesain = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtKaryawan.setBackground(new java.awt.Color(217, 217, 217));
        txtKaryawan.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtKaryawan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtKaryawan.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtKaryawan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtKaryawanFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtKaryawanFocusLost(evt);
            }
        });
        txtKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKaryawanActionPerformed(evt);
            }
        });
        getContentPane().add(txtKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 320, 20));

        txtNama.setBackground(new java.awt.Color(217, 217, 217));
        txtNama.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtNama.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtNama.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNamaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNamaFocusLost(evt);
            }
        });
        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        getContentPane().add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 320, 20));

        txtNoTelp.setBackground(new java.awt.Color(217, 217, 217));
        txtNoTelp.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtNoTelp.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtNoTelp.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNoTelp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNoTelpFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNoTelpFocusLost(evt);
            }
        });
        txtNoTelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoTelpActionPerformed(evt);
            }
        });
        getContentPane().add(txtNoTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, 320, 20));

        jAlamat.setBackground(new java.awt.Color(217, 217, 217));
        jAlamat.setColumns(20);
        jAlamat.setRows(5);
        jAlamat.setBorder(null);
        jAlamat.setSelectionColor(new java.awt.Color(217, 217, 217));
        jScrollPanel1.setViewportView(jAlamat);

        getContentPane().add(jScrollPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 140, 330, 100));

        jKaryawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jKaryawan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, 700, 290));

        btnTambah.setBackground(new java.awt.Color(47, 171, 225));
        btnTambah.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Tambah.png"))); // NOI18N
        btnTambah.setText(" Tambah");
        btnTambah.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTambah.setBorderPainted(false);
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        getContentPane().add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 160, 48));

        btnEdit.setBackground(new java.awt.Color(47, 171, 225));
        btnEdit.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit.png"))); // NOI18N
        btnEdit.setText("  Edit");
        btnEdit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEdit.setBorderPainted(false);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 320, 160, 48));

        btnHapus.setBackground(new java.awt.Color(255, 0, 0));
        btnHapus.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Hapus.png"))); // NOI18N
        btnHapus.setText("  Hapus");
        btnHapus.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHapus.setBorderPainted(false);
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        getContentPane().add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 320, 160, 48));

        txtPassword.setBackground(new java.awt.Color(217, 217, 217));
        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPassword.setToolTipText("");
        txtPassword.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 272, 320, 20));

        jUtama.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jUtama.setEnabled(false);
        jUtama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jUtamaFocusGained(evt);
            }
        });
        jUtama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jUtamaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jUtamaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jUtamaMouseExited(evt);
            }
        });
        getContentPane().add(jUtama, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 112, 340, 113));

        jPelanggan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPelanggan.setEnabled(false);
        jPelanggan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPelangganFocusGained(evt);
            }
        });
        jPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPelangganMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPelangganMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPelangganMouseExited(evt);
            }
        });
        getContentPane().add(jPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 222, 340, 111));

        jTransaksi.setToolTipText("");
        jTransaksi.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTransaksi.setEnabled(false);
        jTransaksi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTransaksiFocusGained(evt);
            }
        });
        jTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTransaksiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTransaksiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTransaksiMouseExited(evt);
            }
        });
        getContentPane().add(jTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 340, 111));

        jLayanan.setToolTipText("");
        jLayanan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jLayanan.setEnabled(false);
        jLayanan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLayananFocusGained(evt);
            }
        });
        jLayanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLayananMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLayananMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLayananMouseExited(evt);
            }
        });
        getContentPane().add(jLayanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 439, 340, 110));

        jKaryawan1.setToolTipText("");
        jKaryawan1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jKaryawan1.setEnabled(false);
        jKaryawan1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jKaryawan1FocusGained(evt);
            }
        });
        jKaryawan1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jKaryawan1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jKaryawan1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jKaryawan1MouseExited(evt);
            }
        });
        getContentPane().add(jKaryawan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 546, 340, 110));

        jTentang.setToolTipText("");
        jTentang.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTentang.setEnabled(false);
        jTentang.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTentangFocusGained(evt);
            }
        });
        jTentang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTentangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTentangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTentangMouseExited(evt);
            }
        });
        getContentPane().add(jTentang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 654, 340, 57));

        jKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jKeluarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jKeluarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jKeluarMouseExited(evt);
            }
        });
        getContentPane().add(jKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 710, 342, 60));

        jDesain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/FKaryawan.png"))); // NOI18N
        getContentPane().add(jDesain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtKaryawanFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtKaryawanFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKaryawanFocusGained

    private void txtKaryawanFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtKaryawanFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKaryawanFocusLost

    private void txtKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKaryawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKaryawanActionPerformed

    private void txtNamaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNamaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaFocusGained

    private void txtNamaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNamaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaFocusLost

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void txtNoTelpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNoTelpFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoTelpFocusGained

    private void txtNoTelpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNoTelpFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoTelpFocusLost

    private void txtNoTelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoTelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoTelpActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed

        // Ambil data dari input form
        String idKaryawan = txtKaryawan.getText();
        String nama = txtNama.getText();
        String password = String.valueOf(txtPassword.getPassword()); // Mengambil password dari JPasswordField
        String noTelp = txtNoTelp.getText();
        String alamat = jAlamat.getText();

// Validasi input tidak boleh kosong
        if (idKaryawan.isEmpty() || nama.isEmpty() || noTelp.isEmpty() || password.isEmpty() || alamat.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua field harus diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

// Validasi tambahan (contoh: No. Telepon harus angka)
        if (!noTelp.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "No. Telepon harus berupa angka!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (password.length() < 8) {
            JOptionPane.showMessageDialog(this, "Password minimal 8 karakter!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

// Validasi ID unik
        try (java.sql.Connection conn = Config.configDB()) {
            String checkIdSql = "SELECT COUNT(*) AS count FROM t_karyawan WHERE id_karyawan = ?";
            java.sql.PreparedStatement pstCheck = conn.prepareStatement(checkIdSql);
            pstCheck.setString(1, idKaryawan);
            java.sql.ResultSet rs = pstCheck.executeQuery();
            if (rs.next() && rs.getInt("count") > 0) {
                JOptionPane.showMessageDialog(this, "ID Karyawan sudah ada! Gunakan ID lain.", "Peringatan", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal memeriksa ID: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

// Proses penyimpanan data tanpa hashing
        try {
            String sql = "INSERT INTO t_karyawan (id_karyawan, nama, password, no_telp, alamat) VALUES (?, ?, ?, ?, ?)";
            java.sql.Connection conn = Config.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);

            // Simpan password asli tanpa hashing
            pst.setString(1, idKaryawan);
            pst.setString(2, nama);
            pst.setString(3, password); // Simpan password asli
            pst.setString(4, noTelp);
            pst.setString(5, alamat);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan!", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            load_table(); // Muat ulang tabel
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal menambahkan data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        if (!isEditing) {
            // Jika mode edit belum aktif
            int selectedRow = jKaryawan.getSelectedRow();
            if (selectedRow == -1) {
                JOptionPane.showMessageDialog(this, "Pilih karyawan yang ingin diedit", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Ambil data dari tabel
            String id = jKaryawan.getValueAt(selectedRow, 1).toString(); // Kolom ID Karyawan
            String nama = jKaryawan.getValueAt(selectedRow, 2).toString(); // Kolom Nama
            String noTelp = jKaryawan.getValueAt(selectedRow, 3).toString(); // Kolom No Telepon
            String alamat = jKaryawan.getValueAt(selectedRow, 4).toString(); // Kolom Alamat

            // Isi form dengan data yang benar
            txtKaryawan.setText(id);
            txtNama.setText(nama);
            txtNoTelp.setText(noTelp);
            jAlamat.setText(alamat);

            // Ubah status menjadi editing
            isEditing = true;
            btnEdit.setText("Simpan"); // Ubah tombol menjadi Simpan
        } else {
            // Jika mode edit aktif, simpan perubahan
            String id = txtKaryawan.getText();
            String nama = txtNama.getText();
            String noTelp = txtNoTelp.getText();
            String alamat = jAlamat.getText();
            String passwordBaru = new String(txtPassword.getPassword()); // Ambil password baru (opsional)

            // Validasi input
            if (id.isEmpty() || nama.isEmpty() || noTelp.isEmpty() || alamat.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Semua field (kecuali password) harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            try (java.sql.Connection conn = Config.configDB()) {
                // Jika password baru diisi, masukkan ke dalam query
                String sql;
                if (!passwordBaru.isEmpty()) {
                    // Jika password baru diisi, update password juga
                    sql = "UPDATE t_karyawan SET nama = ?, no_telp = ?, alamat = ?, password = ? WHERE id_karyawan = ?";
                } else {
                    // Jika password kosong, hanya update field lainnya
                    sql = "UPDATE t_karyawan SET nama = ?, no_telp = ?, alamat = ? WHERE id_karyawan = ?";
                }

                var pst = conn.prepareStatement(sql);
                pst.setString(1, nama);
                pst.setString(2, noTelp);
                pst.setString(3, alamat);
                if (!passwordBaru.isEmpty()) {
                    pst.setString(4, passwordBaru); // Simpan password asli (tanpa hash)
                    pst.setString(5, id); // Parameter ID
                } else {
                    pst.setString(4, id); // Parameter ID jika password tidak diubah
                }

                pst.executeUpdate();

                JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!");

                // Muat ulang tabel
                load_table();
            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Gagal memperbarui data: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }

            // Kembali ke mode normal
            isEditing = false;
            btnEdit.setText("Edit");
            txtKaryawan.setEditable(true); // Aktifkan input ID jika diperlukan
            txtPassword.setText(""); // Kosongkan field password
        }
    
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int selectedRow = jKaryawan.getSelectedRow(); // Mendapatkan baris yang dipilih di JTable

        // Cek jika tidak ada baris yang dipilih
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih karyawan yang ingin dihapus", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Ambil ID dari kolom yang sesuai (misalnya kolom ID Karyawan adalah indeks 0)
        String id = jKaryawan.getValueAt(selectedRow, 0).toString();

        // Tampilkan konfirmasi sebelum menghapus
        int confirm = JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try (java.sql.Connection conn = Config.configDB()) {
                // Query untuk menghapus data karyawan berdasarkan ID
                String sql = "DELETE FROM t_karyawan WHERE id_karyawan = ?";
                var pst = conn.prepareStatement(sql);
                pst.setString(1, id); // Set ID karyawan pada parameter query
                pst.executeUpdate(); // Eksekusi query

                // Pesan konfirmasi penghapusan berhasil
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");

                // Muat ulang tabel untuk menampilkan data terbaru
                load_table();
            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Gagal menghapus data: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void jUtamaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jUtamaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jUtamaFocusGained

    private void jUtamaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jUtamaMouseClicked
        // TODO add your handling code here:
        jUtama.setBorder(BorderFactory.createLineBorder(Color.DARK_GRAY, 4));
        jUtama.setBackground(new Color(0, 0, 0, 100));
        jUtama.setOpaque(true);

        Timer timer = new Timer(500, e -> {
            // Menutup frame yang ada
            JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor(jUtama);
            currentFrame.dispose(); // Menutup frame yang ada

            // Membuka kembali frame utama
            FUtama formUtama = new FUtama();
            formUtama.setVisible(true);  // Menampilkan frame utama
        });
        timer.setRepeats(false);  // Pastikan hanya sekali
        timer.start();  // Mulai timer

    }//GEN-LAST:event_jUtamaMouseClicked

    private void jUtamaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jUtamaMouseEntered
        // TODO add your handling code here:
        jUtama.setBorder(BorderFactory.createLineBorder(Color.DARK_GRAY, 4));
    }//GEN-LAST:event_jUtamaMouseEntered

    private void jUtamaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jUtamaMouseExited
        // TODO add your handling code here:

        jUtama.setBorder(null);
        jUtama.setOpaque(false);

    }//GEN-LAST:event_jUtamaMouseExited

    private void jPelangganFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPelangganFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jPelangganFocusGained

    private void jPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPelangganMouseClicked
        // TODO add your handling code here:
        jPelanggan.setBorder(BorderFactory.createLineBorder(Color.DARK_GRAY, 4));
        jPelanggan.setBackground(new Color(0, 0, 0, 100));
        jPelanggan.setOpaque(true);

        Timer timer = new Timer(500, e -> {
            // Menutup frame yang ada
            JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor(jUtama);
            currentFrame.dispose(); // Menutup frame yang ada

            // Membuka kembali frame utama
            FPelanggan formPelanggan = new FPelanggan();
            formPelanggan.setVisible(true);  // Menampilkan frame utama
        });
        timer.setRepeats(false);  // Pastikan hanya sekali
        timer.start();  // Mulai timer
    }//GEN-LAST:event_jPelangganMouseClicked

    private void jPelangganMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPelangganMouseEntered
        // TODO add your handling code here:
        jPelanggan.setBorder(BorderFactory.createLineBorder(Color.DARK_GRAY, 4));
    }//GEN-LAST:event_jPelangganMouseEntered

    private void jPelangganMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPelangganMouseExited
        // TODO add your handling code here:
        jPelanggan.setBorder(null);
        jPelanggan.setOpaque(false);
    }//GEN-LAST:event_jPelangganMouseExited

    private void jTransaksiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTransaksiFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTransaksiFocusGained

    private void jTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTransaksiMouseClicked
        // TODO add your handling code here:
        jTransaksi.setBorder(BorderFactory.createLineBorder(Color.DARK_GRAY, 4));
        jTransaksi.setBackground(new Color(0, 0, 0, 100));
        jTransaksi.setOpaque(true);

        Timer timer = new Timer(500, e -> {
            // Menutup frame yang ada
            JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor(jUtama);
            currentFrame.dispose(); // Menutup frame yang ada

            // Membuka kembali frame utama
            FTransaksi formTransaksi = new FTransaksi();
            formTransaksi.setVisible(true);  // Menampilkan frame utama
        });
        timer.setRepeats(false);  // Pastikan hanya sekali
        timer.start();  // Mulai timer
    }//GEN-LAST:event_jTransaksiMouseClicked

    private void jTransaksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTransaksiMouseEntered
        // TODO add your handling code here:
        jTransaksi.setBorder(BorderFactory.createLineBorder(Color.DARK_GRAY, 4));
    }//GEN-LAST:event_jTransaksiMouseEntered

    private void jTransaksiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTransaksiMouseExited
        // TODO add your handling code here:
        jTransaksi.setBorder(null);
        jTransaksi.setOpaque(false);
    }//GEN-LAST:event_jTransaksiMouseExited

    private void jLayananFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLayananFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jLayananFocusGained

    private void jLayananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLayananMouseClicked
        // TODO add your handling code here:
        jLayanan.setBorder(BorderFactory.createLineBorder(Color.DARK_GRAY, 4));
        jLayanan.setBackground(new Color(0, 0, 0, 100));
        jLayanan.setOpaque(true);

        Timer timer = new Timer(500, e -> {
            // Menutup frame yang ada
            JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor(jUtama);
            currentFrame.dispose(); // Menutup frame yang ada

            // Membuka kembali frame utama
            FLayanan formLayanan = new FLayanan();
            formLayanan.setVisible(true);  // Menampilkan frame utama
        });
        timer.setRepeats(false);  // Pastikan hanya sekali
        timer.start();  // Mulai timer
    }//GEN-LAST:event_jLayananMouseClicked

    private void jLayananMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLayananMouseEntered
        // TODO add your handling code here:
        jLayanan.setBorder(BorderFactory.createLineBorder(Color.DARK_GRAY, 4));
    }//GEN-LAST:event_jLayananMouseEntered

    private void jLayananMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLayananMouseExited
        // TODO add your handling code here:
        jLayanan.setBorder(null);
        jLayanan.setOpaque(false);
    }//GEN-LAST:event_jLayananMouseExited

    private void jKaryawan1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jKaryawan1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jKaryawan1FocusGained

    private void jKaryawan1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jKaryawan1MouseClicked
        // TODO add your handling code here:
        jKaryawan.setBorder(BorderFactory.createLineBorder(Color.DARK_GRAY, 4));
        jKaryawan.setBackground(new Color(0, 0, 0, 100));
        jKaryawan.setOpaque(true);

        Timer timer = new Timer(500, e -> {
            // Menutup frame yang ada
            JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor(jUtama);
            currentFrame.dispose(); // Menutup frame yang ada

            // Membuka kembali frame utama
            FKaryawan formKaryawan = new FKaryawan();
            formKaryawan.setVisible(true);  // Menampilkan frame utama
        });
        timer.setRepeats(false);  // Pastikan hanya sekali
        timer.start();  // Mulai timer
    }//GEN-LAST:event_jKaryawan1MouseClicked

    private void jKaryawan1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jKaryawan1MouseEntered
        // TODO add your handling code here:
        jKaryawan.setBorder(BorderFactory.createLineBorder(Color.DARK_GRAY, 4));
    }//GEN-LAST:event_jKaryawan1MouseEntered

    private void jKaryawan1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jKaryawan1MouseExited
        // TODO add your handling code here:
        jKaryawan.setBorder(null);
        jKaryawan.setOpaque(false);
    }//GEN-LAST:event_jKaryawan1MouseExited

    private void jTentangFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTentangFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTentangFocusGained

    private void jTentangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTentangMouseClicked
        // TODO add your handling code here:
        jTentang.setBorder(BorderFactory.createLineBorder(Color.DARK_GRAY, 4));
        jTentang.setBackground(new Color(0, 0, 0, 100));
        jTentang.setOpaque(true);

        Timer timer = new Timer(500, e -> {
            // Menutup frame yang ada
            JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor(jUtama);
            currentFrame.dispose(); // Menutup frame yang ada

            // Membuka kembali frame utama
            FTentang formTentang = new FTentang();
            formTentang.setVisible(true);  // Menampilkan frame utama
        });
        timer.setRepeats(false);  // Pastikan hanya sekali
        timer.start();  // Mulai timer
    }//GEN-LAST:event_jTentangMouseClicked

    private void jTentangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTentangMouseEntered
        // TODO add your handling code here:
        jTentang.setBorder(BorderFactory.createLineBorder(Color.DARK_GRAY, 4));
    }//GEN-LAST:event_jTentangMouseEntered

    private void jTentangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTentangMouseExited
        // TODO add your handling code here:
        jTentang.setBorder(null);
        //        jTentang.setOpaque(false);
    }//GEN-LAST:event_jTentangMouseExited

    private void jKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jKeluarMouseClicked
        // TODO add your handling code here:
        jKeluar.setBorder(BorderFactory.createLineBorder(Color.DARK_GRAY, 4));
        int response = JOptionPane.showConfirmDialog(this,
            "Apakah Anda yakin ingin keluar?",
            "Konfirmasi Keluar",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE);

        if (response == JOptionPane.YES_OPTION) {
            //            System.exit(0);
            FLogin loginForm = new FLogin();
            loginForm.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jKeluarMouseClicked

    private void jKeluarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jKeluarMouseEntered
        jKeluar.setBorder(BorderFactory.createLineBorder(Color.DARK_GRAY, 4));

    }//GEN-LAST:event_jKeluarMouseEntered

    private void jKeluarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jKeluarMouseExited
        jKeluar.setBorder(null);
        jKeluar.setOpaque(false);
    }//GEN-LAST:event_jKeluarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(FKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(FKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(FKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(FKaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new FKaryawan().setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JTextArea jAlamat;
    private javax.swing.JLabel jDesain;
    private javax.swing.JTable jKaryawan;
    private javax.swing.JLabel jKaryawan1;
    private javax.swing.JLabel jKeluar;
    private javax.swing.JLabel jLayanan;
    private javax.swing.JLabel jPelanggan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPanel1;
    private javax.swing.JLabel jTentang;
    private javax.swing.JLabel jTransaksi;
    private javax.swing.JLabel jUtama;
    private javax.swing.JTextField txtKaryawan;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNoTelp;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
