/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package halaman;

import java.awt.Color;
import javax.swing.SwingUtilities;
import javax.swing.plaf.basic.BasicProgressBarUI;

/**
 *
 * @author Kelompok 2
 */
public class FLoad extends javax.swing.JFrame {
    
    /**
     * Creates new form FLoad
     */
    public FLoad() {
        initComponents();
        setLocationRelativeTo(null);
        
           // Mengatur warna indikator progress
        progress.setForeground(new Color(76, 135, 200)); // Mengubah warna indikator progress
        progress.setBackground(Color.GRAY);  // Latar belakang progress bar

        // Mengubah UI default dari progress bar agar warnanya lebih mudah dikontrol
        progress.setUI(new BasicProgressBarUI() {
            @Override
            protected void paintDeterminate(java.awt.Graphics g, javax.swing.JComponent c) {
                // Mengubah gaya render untuk progres
                super.paintDeterminate(g, c);
                g.setColor(new Color(76, 135, 200)); // Ganti dengan warna indikator RGB
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progress = new javax.swing.JProgressBar();
        persen = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        progress.setBackground(new java.awt.Color(76, 135, 200));
        getContentPane().add(progress, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 544, 880, 60));

        persen.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        persen.setForeground(new java.awt.Color(47, 171, 240));
        persen.setText("0%");
        getContentPane().add(persen, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 510, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/FLoad.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FLoad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FLoad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FLoad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FLoad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        // Set the Nimbus look and feel
        SwingUtilities.invokeLater(() -> {
            FLoad l = new FLoad(); // Buat instance FLoad
            l.setVisible(true);    // Tampilkan JFrame FLoad

            // Buat thread untuk simulasi progress loading
            new Thread(() -> {
                try {
                    for (int x = 0; x <= 100; x++) {
                        Thread.sleep(30); // Simulasi loading
                        l.persen.setText(x + "%"); // Update persen
                        l.progress.setValue(x);    // Update progress bar

                        if (x == 100) { // Jika loading selesai
                            l.setVisible(false); // Sembunyikan JFrame FLoad
                            l.dispose();         // Tutup JFrame FLoad sepenuhnya

                            // Tampilkan JFrame FLogin
                            SwingUtilities.invokeLater(() -> {
                                FLogin m = new FLogin(); // Inisialisasi JFrame FLogin
                                m.setVisible(true);     // Tampilkan JFrame FLogin
                            });
                        }
                    }
                } catch (Exception e) {
                    e.printStackTrace(); // Tangani error jika terjadi
                }
            }).start();
        });
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new FLoad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel persen;
    private javax.swing.JProgressBar progress;
    // End of variables declaration//GEN-END:variables
}
