/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package halaman;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.Timer;

/**
 *
 * @author Kelompok 2
 */
public class FTentang extends javax.swing.JFrame {

    /**
     * Creates new form FAbout
     */
    public FTentang() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jUtama = new javax.swing.JLabel();
        jPelanggan = new javax.swing.JLabel();
        jTransaksi = new javax.swing.JLabel();
        jLayanan = new javax.swing.JLabel();
        jKaryawan = new javax.swing.JLabel();
        jTentang = new javax.swing.JLabel();
        jKeluar = new javax.swing.JLabel();
        jDesain = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jUtama.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jUtama.setEnabled(false);
        jUtama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jUtamaFocusGained(evt);
            }
        });
        jUtama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jUtamaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jUtamaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jUtamaMouseExited(evt);
            }
        });
        getContentPane().add(jUtama, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 112, 340, 113));

        jPelanggan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPelanggan.setEnabled(false);
        jPelanggan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPelangganFocusGained(evt);
            }
        });
        jPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPelangganMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPelangganMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPelangganMouseExited(evt);
            }
        });
        getContentPane().add(jPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 222, 340, 111));

        jTransaksi.setToolTipText("");
        jTransaksi.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTransaksi.setEnabled(false);
        jTransaksi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTransaksiFocusGained(evt);
            }
        });
        jTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTransaksiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTransaksiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTransaksiMouseExited(evt);
            }
        });
        getContentPane().add(jTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 340, 111));

        jLayanan.setToolTipText("");
        jLayanan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jLayanan.setEnabled(false);
        jLayanan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLayananFocusGained(evt);
            }
        });
        jLayanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLayananMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLayananMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLayananMouseExited(evt);
            }
        });
        getContentPane().add(jLayanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 439, 340, 110));

        jKaryawan.setToolTipText("");
        jKaryawan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jKaryawan.setEnabled(false);
        jKaryawan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jKaryawanFocusGained(evt);
            }
        });
        jKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jKaryawanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jKaryawanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jKaryawanMouseExited(evt);
            }
        });
        getContentPane().add(jKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 546, 340, 110));

        jTentang.setToolTipText("");
        jTentang.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTentang.setEnabled(false);
        jTentang.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTentangFocusGained(evt);
            }
        });
        jTentang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTentangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTentangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTentangMouseExited(evt);
            }
        });
        getContentPane().add(jTentang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 654, 340, 57));

        jKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jKeluarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jKeluarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jKeluarMouseExited(evt);
            }
        });
        getContentPane().add(jKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 710, 342, 60));

        jDesain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/FAbout.png"))); // NOI18N
        getContentPane().add(jDesain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jUtamaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jUtamaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jUtamaFocusGained

    private void jUtamaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jUtamaMouseClicked
        // TODO add your handling code here:
        jUtama.setBorder(BorderFactory.createLineBorder(Color.DARK_GRAY, 4));
        jUtama.setBackground(new Color(0, 0, 0, 100));
        jUtama.setOpaque(true);

        Timer timer = new Timer(500, e -> {
            // Menutup frame yang ada
            JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor(jUtama);
            currentFrame.dispose(); // Menutup frame yang ada

            // Membuka kembali frame utama
            FUtama formUtama = new FUtama();
            formUtama.setVisible(true);  // Menampilkan frame utama
        });
        timer.setRepeats(false);  // Pastikan hanya sekali
        timer.start();  // Mulai timer

    }//GEN-LAST:event_jUtamaMouseClicked

    private void jUtamaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jUtamaMouseEntered
        // TODO add your handling code here:
        jUtama.setBorder(BorderFactory.createLineBorder(Color.DARK_GRAY, 4));
    }//GEN-LAST:event_jUtamaMouseEntered

    private void jUtamaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jUtamaMouseExited
        // TODO add your handling code here:

        jUtama.setBorder(null);
        jUtama.setOpaque(false);

    }//GEN-LAST:event_jUtamaMouseExited

    private void jPelangganFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPelangganFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jPelangganFocusGained

    private void jPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPelangganMouseClicked
        // TODO add your handling code here:
        jPelanggan.setBorder(BorderFactory.createLineBorder(Color.DARK_GRAY, 4));
        jPelanggan.setBackground(new Color(0, 0, 0, 100));
        jPelanggan.setOpaque(true);

        Timer timer = new Timer(500, e -> {
            // Menutup frame yang ada
            JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor(jUtama);
            currentFrame.dispose(); // Menutup frame yang ada

            // Membuka kembali frame utama
            FPelanggan formPelanggan = new FPelanggan();
            formPelanggan.setVisible(true);  // Menampilkan frame utama
        });
        timer.setRepeats(false);  // Pastikan hanya sekali
        timer.start();  // Mulai timer
    }//GEN-LAST:event_jPelangganMouseClicked

    private void jPelangganMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPelangganMouseEntered
        // TODO add your handling code here:
        jPelanggan.setBorder(BorderFactory.createLineBorder(Color.DARK_GRAY, 4));
    }//GEN-LAST:event_jPelangganMouseEntered

    private void jPelangganMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPelangganMouseExited
        // TODO add your handling code here:
        jPelanggan.setBorder(null);
        jPelanggan.setOpaque(false);
    }//GEN-LAST:event_jPelangganMouseExited

    private void jTransaksiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTransaksiFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTransaksiFocusGained

    private void jTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTransaksiMouseClicked
        // TODO add your handling code here:
        jTransaksi.setBorder(BorderFactory.createLineBorder(Color.DARK_GRAY, 4));
        jTransaksi.setBackground(new Color(0, 0, 0, 100));
        jTransaksi.setOpaque(true);

        Timer timer = new Timer(500, e -> {
            // Menutup frame yang ada
            JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor(jUtama);
            currentFrame.dispose(); // Menutup frame yang ada

            // Membuka kembali frame utama
            FTransaksi formTransaksi = new FTransaksi();
            formTransaksi.setVisible(true);  // Menampilkan frame utama
        });
        timer.setRepeats(false);  // Pastikan hanya sekali
        timer.start();  // Mulai timer
    }//GEN-LAST:event_jTransaksiMouseClicked

    private void jTransaksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTransaksiMouseEntered
        // TODO add your handling code here:
        jTransaksi.setBorder(BorderFactory.createLineBorder(Color.DARK_GRAY, 4));
    }//GEN-LAST:event_jTransaksiMouseEntered

    private void jTransaksiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTransaksiMouseExited
        // TODO add your handling code here:
        jTransaksi.setBorder(null);
        jTransaksi.setOpaque(false);
    }//GEN-LAST:event_jTransaksiMouseExited

    private void jLayananFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLayananFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jLayananFocusGained

    private void jLayananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLayananMouseClicked
        // TODO add your handling code here:
        jLayanan.setBorder(BorderFactory.createLineBorder(Color.DARK_GRAY, 4));
        jLayanan.setBackground(new Color(0, 0, 0, 100));
        jLayanan.setOpaque(true);

        Timer timer = new Timer(500, e -> {
            // Menutup frame yang ada
            JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor(jUtama);
            currentFrame.dispose(); // Menutup frame yang ada

            // Membuka kembali frame utama
            FLayanan formLayanan = new FLayanan();
            formLayanan.setVisible(true);  // Menampilkan frame utama
        });
        timer.setRepeats(false);  // Pastikan hanya sekali
        timer.start();  // Mulai timer
    }//GEN-LAST:event_jLayananMouseClicked

    private void jLayananMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLayananMouseEntered
        // TODO add your handling code here:
        jLayanan.setBorder(BorderFactory.createLineBorder(Color.DARK_GRAY, 4));
    }//GEN-LAST:event_jLayananMouseEntered

    private void jLayananMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLayananMouseExited
        // TODO add your handling code here:
        jLayanan.setBorder(null);
        jLayanan.setOpaque(false);
    }//GEN-LAST:event_jLayananMouseExited

    private void jKaryawanFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jKaryawanFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jKaryawanFocusGained

    private void jKaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jKaryawanMouseClicked
        // TODO add your handling code here:
        jKaryawan.setBorder(BorderFactory.createLineBorder(Color.DARK_GRAY, 4));
        jKaryawan.setBackground(new Color(0, 0, 0, 100));
        jKaryawan.setOpaque(true);

        Timer timer = new Timer(500, e -> {
            // Menutup frame yang ada
            JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor(jUtama);
            currentFrame.dispose(); // Menutup frame yang ada

            // Membuka kembali frame utama
            FKaryawan formKaryawan = new FKaryawan();
            formKaryawan.setVisible(true);  // Menampilkan frame utama
        });
        timer.setRepeats(false);  // Pastikan hanya sekali
        timer.start();  // Mulai timer
    }//GEN-LAST:event_jKaryawanMouseClicked

    private void jKaryawanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jKaryawanMouseEntered
        // TODO add your handling code here:
        jKaryawan.setBorder(BorderFactory.createLineBorder(Color.DARK_GRAY, 4));
    }//GEN-LAST:event_jKaryawanMouseEntered

    private void jKaryawanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jKaryawanMouseExited
        // TODO add your handling code here:
        jKaryawan.setBorder(null);
        jKaryawan.setOpaque(false);
    }//GEN-LAST:event_jKaryawanMouseExited

    private void jTentangFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTentangFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTentangFocusGained

    private void jTentangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTentangMouseClicked
        // TODO add your handling code here:
        jTentang.setBorder(BorderFactory.createLineBorder(Color.DARK_GRAY, 4));
        jTentang.setBackground(new Color(0, 0, 0, 100));
        jTentang.setOpaque(true);

        Timer timer = new Timer(500, e -> {
            // Menutup frame yang ada
            JFrame currentFrame = (JFrame) SwingUtilities.getWindowAncestor(jUtama);
            currentFrame.dispose(); // Menutup frame yang ada

            // Membuka kembali frame utama
            FTentang formTentang = new FTentang();
            formTentang.setVisible(true);  // Menampilkan frame utama
        });
        timer.setRepeats(false);  // Pastikan hanya sekali
        timer.start();  // Mulai timer
    }//GEN-LAST:event_jTentangMouseClicked

    private void jTentangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTentangMouseEntered
        // TODO add your handling code here:
        jTentang.setBorder(BorderFactory.createLineBorder(Color.DARK_GRAY, 4));
    }//GEN-LAST:event_jTentangMouseEntered

    private void jTentangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTentangMouseExited
        // TODO add your handling code here:
        jTentang.setBorder(null);
        //        jTentang.setOpaque(false);
    }//GEN-LAST:event_jTentangMouseExited

    private void jKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jKeluarMouseClicked
        // TODO add your handling code here:
        jKeluar.setBorder(BorderFactory.createLineBorder(Color.DARK_GRAY, 4));
        int response = JOptionPane.showConfirmDialog(this,
            "Apakah Anda yakin ingin keluar?",
            "Konfirmasi Keluar",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE);

        if (response == JOptionPane.YES_OPTION) {
            //            System.exit(0);
            FLogin loginForm = new FLogin();
            loginForm.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jKeluarMouseClicked

    private void jKeluarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jKeluarMouseEntered
        jKeluar.setBorder(BorderFactory.createLineBorder(Color.DARK_GRAY, 4));

    }//GEN-LAST:event_jKeluarMouseEntered

    private void jKeluarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jKeluarMouseExited
        jKeluar.setBorder(null);
        jKeluar.setOpaque(false);
    }//GEN-LAST:event_jKeluarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FTentang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FTentang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FTentang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FTentang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FTentang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jDesain;
    private javax.swing.JLabel jKaryawan;
    private javax.swing.JLabel jKeluar;
    private javax.swing.JLabel jLayanan;
    private javax.swing.JLabel jPelanggan;
    private javax.swing.JLabel jTentang;
    private javax.swing.JLabel jTransaksi;
    private javax.swing.JLabel jUtama;
    // End of variables declaration//GEN-END:variables
}
